### ISSUE TITLE
Support right side trigger key

### ISSUE THREAD

**Issue by mgher668** [flawyte/fast-scroll#18]
I use the mouse with my left hand. The left side trigger key is uncomfortable for me. So can you consider supporting right side trigger key?

**Comment by flawyte** [comment]
Hi, thanks for the feedback !
And sorry for the response delay... I've been very busy lately.
I just published version 4.1 on the Chrome Webstore with what you asked for :)
It should take a few hours for Google to validate and deploy it.

**Comment by mgher668** [comment]
It works, thank you so much.

**Comment by flawyte** [comment]
No problem 👍
If you enjoy the extension don't hesitate to rate it on the chrome web store 😉
